### ISSUE TITLE
デザインスキン＆パーツのGutenberg統合

### ISSUE THREAD

**Issue by lqdjp** [lqdjp/liquid-press#231]
functions.php, style.css, css/block.css, css/editor-style.css, js/block-style.js, js/common.min.js

**Comment by kumagiti** [comment]
完了の目標はいつころでしょうか？

**Comment by lqdjp** [comment]
> 完了の目標はいつころでしょうか？

ブロックに変換可能なものについて対応し、今週中のリリース予定です。

**Comment by lqdjp** [comment]
fix.
